(module
 (table 0 anyfunc)
 (memory $0 1)
 (data (i32.const 16) "Hello world\00")
 (export "memory" (memory $0))
 (export "main" (func $main))
 (export "test" (func $test))
 (func $main (; 0 ;) (result i32)
  (i32.const 42)
 )
 (func $test (; 1 ;) (result i32)
  (i32.const 16)
 )
)
